name: Tox List
description: >-
  Runs 'tox -l' on your repository and sets the output to a JSON list of environments
inputs:
  tox-args:
    descrition: Additional CLI arguments to tox
    required: true
    default: ''
outputs:
  tox-envs:
    description: A JSON list of tox environments
    value: ${{ steps.envs.outputs.envs }}
runs:
  using: composite
  steps:
    - name: Run tox with args and get output
      id: envs
      shell: bash
      run: |
        set -e -o pipefail
        if ! command -v tox;
        then
          python -m venv ${{ github.action_path }}/venv
          source ${{ github.action_path }}/venv/bin/activate
          python -m pip install tox
        fi
        envs="$(tox -ql ${{ inputs.tox-args }} | python -c 'import sys; import json; print(json.dumps(sys.stdin.read().strip().split("\n")))')"
        echo "::set-output name=envs::${envs}"
