name: Tox List
description: >-
  Runs 'tox -l' on your repository and sets the output to a JSON list of environments
inputs:
  tox-args:
    descrition: Additional CLI arguments to tox
    required: true
    default: ''
outputs:
  tox-envs:
    description: A JSON list of tox environments
    value: ${{ steps.envs.outputs.envs }}
runs:
  using: composite
  steps:
    - name: Run tox with args and get output
      id: envs
      shell: bash
      run: |
        set -ex -o pipefail
        # Destination for the virtualenv
        if [ "${RUNNER_OS}" == "Windows" ];
        then
          venv="${{ github.action_path }}\\venv"
          activate="${venv}\\Scripts\\activate"
          prog="python"
        else
          venv="${{ github.action_path }}/venv"
          activate="${venv}/bin/activate"
          prog="python3"
        fi
        # Ensure that tox exists
        if ! command -v tox;
        then
          # Create the virtualenv
          "${prog}" -m venv "${venv}"

          # Activate the virtualenv
          source "${activate}"

          # Install tox
          python -m pip install tox
        fi
        envs="$(tox -ql ${{ inputs.tox-args }} 2>/dev/null | "${prog}" "${{ github.action_path }}/do_the_splits.py")"
        echo "::set-output name=envs::${envs}"
